rules:
  idiomatic:
    custom-has-key-construct:
    no-defined-entrypoint:
      level: ignore
  style:
    # Style category safe to ignore, but good to follow modern conventions
    # Address these as you see fit
    # https://docs.styra.com/regal/category/style
    external-reference:
      level: ignore
    file-length:
      level: ignore
    line-length:
      level: ignore
    opa-fmt:
      level: ignore
    rule-length:
      level: ignore
  testing:
    test-outside-test-package:
      # https://docs.styra.com/regal/rules/testing/test-outside-test-package
      level: ignore