apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: example-name
rules:
  - apiGroups: [""] # Add the * (Wildcard) to fail on policy rule
    resources: ["pods", "deployments", "configmaps", "services", "endpoints"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["get", "watch", "list"] # Add any values from "create", "update", "patch" to fail on policy rule
  - apiGroups: ["certificates.k8s.io"]
    resources: ["certificatesigningrequests/approval"]
    verbs: [""] # Add "update" or "patch" from verbs to fail on policy rule
  - apiGroups: ["certificates.k8s.io"]
    resources: ["", "signers"]
    verbs: [""] # Add "approve" from verbs to fail on policy rule
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["rolebindings", "clusterrolebindings"]
    verbs: [""] # Add "bind" from verbs to fail on policy rule
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "clusterroles"]
    verbs: [""] # Add "escalate" from verbs to fail on policy rule
  - apiGroups: [""]
    resources: ["nodes/proxy", "pods/exec"]
    verbs: [""] # Add "create" from verbs to fail on policy rule
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  