name: Run OPA Tests
on:
  push:
    branches: [ "main" ,"feature/docker-iac" ]
  pull_request:
    branches: [ "main" ,"feature/docker-iac" ]
jobs:
  Run-OPA-Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2
      with:
        version: latest

    - name: Run OPA Tests
      run: opa test internal/checker/dockerfile/rules -v

    - name: Setup Regal
      uses: StyraInc/setup-regal@v0.2.0
      with:
        version: v0.11.0
    - run: regal lint --format=github internal/checker/dockerfile/rules
