name: Run OPA Tests
on:
  push:
    branches: [ "main" , "feature/terraform-oci-development"]
  pull_request:
    branches: [ "main" , "feature/terraform-oci-development"]
jobs:
  Run-OPA-Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2
      with:
        version: latest

    - name: Run OPA Tests
      run: opa test internal/checker -v